"""Epicor BAQ Reference — schema definitions for AI context and query building."""

BAQ_CATALOG = {
    "ARStaffMtgRpt": {
        "purpose": "AR Aging Report — outstanding invoices with aging buckets",
        "keywords": ["invoice", "aging", "AR", "accounts receivable", "past due", "owed", "balance", "payment", "overdue"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Calculated_Current": "numeric",
            "Calculated_DBT": "integer",
            "Calculated_Debt130": "numeric",
            "Calculated_Debt3160": "numeric",
            "Calculated_Debt6190": "numeric",
            "Calculated_Debt91": "numeric",
            "Customer_CustID": "string",
            "Customer_Name": "string",
            "InvcHead_DueDate": "date",
            "InvcHead_InvoiceBal": "numeric",
            "InvcHead_InvoiceDate": "date",
            "InvcHead_InvoiceNum": "integer",
            "InvcHead_Posted": "boolean",
            "InvcHead_TermsCode": "string",
        },
    },
    "BMC-500DailyShipments": {
        "purpose": "BMC open orders with shipment-readiness and on-hand inventory",
        "keywords": ["open order", "BMC", "ready to ship", "on hand", "shipment ready", "credit hold"],
        "companies": ["BMC"],
        "fields": {
            "Calculated_AcctNoBilling": "integer",
            "Calculated_NoAcctNoBill": "integer",
            "Calculated_OnHandQTY": "numeric",
            "Calculated_OpenValue": "numeric",
            "Calculated_Openqty": "numeric",
            "Calculated_Ordertotal": "numeric",
            "Customer_Company": "string",
            "Customer_CreditHold": "boolean",
            "Customer_CustID": "string",
            "Customer_Name": "string",
            "OrderDtl_Company": "string",
            "OrderDtl_DocDiscount": "numeric",
            "OrderDtl_DocExtPriceDtl": "numeric",
            "OrderDtl_LineDesc": "string",
            "OrderDtl_OpenLine": "boolean",
            "OrderDtl_OrderComment": "string",
            "OrderDtl_ProdCode": "string",
            "OrderDtl_QuoteLine": "integer",
            "OrderDtl_QuoteNum": "integer",
            "OrderDtl_SalesCatID": "string",
            "OrderDtl_ShortChar02": "string",
            "OrderDtl_UnitPrice": "numeric",
            "OrderDtl_XPartNum": "string",
            "OrderDtl_XRevisionNum": "string",
            "OrderHed_Company": "string",
            "OrderHed_CreditOverride": "boolean",
            "OrderHed_CustNum": "integer",
            "OrderHed_OrderComment": "string",
            "OrderHed_OrderDate": "date",
            "OrderHed_OrderHeld": "boolean",
            "OrderHed_OrderNum": "integer",
            "OrderHed_PONum": "string",
            "OrderHed_PayAccount": "string",
            "OrderHed_PayFlag": "string",
            "OrderHed_SalesRepList": "string",
            "OrderHed_ShortChar01": "string",
            "OrderHed_ShortChar03": "string",
            "OrderRel_BuyToOrder": "boolean",
            "OrderRel_Company": "string",
            "OrderRel_DropShip": "boolean",
            "OrderRel_NeedByDate": "date",
            "OrderRel_OpenRelease": "boolean",
            "OrderRel_OrderLine": "integer",
            "OrderRel_OrderNum": "integer",
            "OrderRel_OrderRelNum": "integer",
            "OrderRel_PartNum": "string",
            "OrderRel_Plant": "string",
            "OrderRel_ReqDate": "date",
            "OrderRel_RevisionNum": "string",
            "OrderRel_SellingReqQty": "numeric",
            "OrderRel_ShipToNum": "string",
            "OrderRel_ShipViaCode": "string",
            "ProdGrup_Company": "string",
            "ProdGrup_Description": "string",
            "ShipVia_Company": "string",
            "ShipVia_Description": "string",
        },
    },
    "BMC-LaborDtlMA": {
        "purpose": "Labor transaction history — who worked on what, hours, scrap, rework",
        "keywords": ["labor", "hours", "employee", "scrap", "rework", "production hours", "who worked"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "EmpBasic_Name": "string",
            "JobOper_OpDesc": "string",
            "LaborDtl_ActiveTrans": "boolean",
            "LaborDtl_AssemblySeq": "integer",
            "LaborDtl_DiscrepQty": "numeric",
            "LaborDtl_JobNum": "string",
            "LaborDtl_LaborHrs": "numeric",
            "LaborDtl_LaborQty": "numeric",
            "LaborDtl_OpCode": "string",
            "LaborDtl_OpComplete": "boolean",
            "LaborDtl_OprSeq": "integer",
            "LaborDtl_PayrollDate": "date",
            "LaborDtl_ReWork": "boolean",
            "LaborDtl_ReworkReasonCode": "string",
            "LaborDtl_ScrapQty": "numeric",
            "LaborDtl_ScrapReasonCode": "string",
        },
    },
    "GPT-Backlog": {
        "purpose": "Sales order backlog — ONLY open/unfulfilled order lines with quantities, values, dates. Will NOT return closed/shipped orders. For general order status lookup, use GPT_Open_Orders instead.",
        "keywords": ["backlog", "open order", "on order", "delivery date", "order value", "due", "PO", "purchase order"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Calculated_OpenQty": "numeric",
            "Calculated_OpenValue": "numeric",
            "Customer_CustID": "string",
            "Customer_Name": "string",
            "OrderDtl_DocUnitPrice": "numeric",
            "OrderDtl_LineDesc": "string",
            "OrderDtl_OpenLine": "boolean",
            "OrderDtl_ProdCode": "string",
            "OrderDtl_XPartNum": "string",
            "OrderHed_Company": "string",
            "OrderHed_CustNum": "integer",
            "OrderHed_IndustrySegment_c": "string",
            "OrderHed_OrderDate": "date",
            "OrderHed_OrderNum": "integer",
            "OrderHed_PONum": "string",
            "OrderRel_NeedByDate": "date",
            "OrderRel_OpenRelease": "boolean",
            "OrderRel_OrderLine": "integer",
            "OrderRel_OrderNum": "integer",
            "OrderRel_OrderRelNum": "integer",
            "OrderRel_PartNum": "string",
            "OrderRel_Plant": "string",
            "OrderRel_ReqDate": "date",
            "OrderRel_SellingReqQty": "numeric",
            "OrderRel_ShipToNum": "string",
            "OrderRel_ShipViaCode": "string",
            "OrderRel_VendorNum": "integer",
            "ShipVia_Description": "string",
        },
    },
    "GPT-DailyShipping": {
        "purpose": "Recent shipments report (last ~30 days) — NO FILTERING SUPPORTED. Returns all recent shipments. Do NOT use $filter with this BAQ. Only use this to see what shipped recently, not to look up a specific order.",
        "keywords": ["shipped recently", "recent shipping", "today shipments", "daily shipping report"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Calculated_LineValue": "numeric",
            "Calculated_ShipQty": "integer",
            "Customer_Address1": "string",
            "Customer_City": "string",
            "Customer_Name": "string",
            "Customer_State": "string",
            "Customer_Zip": "string",
            "OrderDtl_NeedByDate": "date",
            "OrderDtl_OrderNum": "integer",
            "OrderDtl_ProdCode": "string",
            "OrderHed_EntryPerson": "string",
            "OrderHed_PONum": "string",
            "OrderRel_ReqDate": "date",
            "SalesRep_EMailAddress": "string",
            "SalesRep_Name": "string",
            "ShipDtl_JobNum": "string",
            "ShipDtl_LineDesc": "string",
            "ShipDtl_OrderLine": "integer",
            "ShipDtl_PartNum": "string",
            "ShipHead_PackNum": "integer",
            "ShipHead_ShipDate": "date",
            "ShipHead_ShipViaCode": "string",
            "ShipHead_TrackingNumber": "string",
            "ShipTo_Address1": "string",
            "ShipTo_City": "string",
            "ShipTo_Country": "string",
            "ShipTo_HubspotID_c": "string",
            "ShipTo_Name": "string",
            "ShipTo_State": "string",
            "ShipTo_ZIP": "string",
        },
    },
    "GPT-InventoryCosts": {
        "purpose": "Inventory on-hand with cost breakdown by warehouse/bin",
        "keywords": ["inventory", "stock", "on hand", "warehouse", "bin", "available", "part", "cost"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Calculated_Burdencost": "numeric",
            "Calculated_LaborCost": "numeric",
            "Calculated_MTLBurden": "numeric",
            "Calculated_Matcost": "numeric",
            "Calculated_Subcost": "numeric",
            "Calculated_TotalMaterialCost": "numeric",
            "PartBin_BinNum": "string",
            "PartBin_LotNum": "string",
            "PartBin_OnhandQty": "numeric",
            "PartCost_CostID": "string",
            "PartWhse_Company": "string",
            "PartWhse_CountedDate": "string",
            "PartWhse_PartNum": "string",
            "PartWhse_WarehouseCode": "string",
            "Part_ClassID": "string",
            "Part_PartDescription": "string",
            "Warehse_Description": "string",
            "Warehse_Plant": "string",
        },
    },
    "GPT-OpenPO": {
        "purpose": "Open purchase orders — vendor deliveries, due dates, quantities, linked jobs",
        "keywords": ["purchase order", "PO", "vendor", "supplier", "buying", "on order from", "material", "delivery"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Calculated_QtyBalance": "numeric",
            "PODetail_BTOOrderLine": "integer",
            "PODetail_BTOOrderNum": "integer",
            "PODetail_LineDesc": "string",
            "PODetail_POLine": "integer",
            "PODetail_PartNum": "string",
            "PODetail_UnitCost": "numeric",
            "POHeader_OrderDate": "date",
            "POHeader_PONum": "integer",
            "POHeader_ShipName": "string",
            "PORel_Company": "string",
            "PORel_DropShip": "boolean",
            "PORel_DueDate": "date",
            "PORel_JobNum": "string",
            "PORel_OpenRelease": "boolean",
            "PORel_OrderLine": "integer",
            "PORel_OrderNum": "integer",
            "PORel_POLine": "integer",
            "PORel_PONum": "integer",
            "PORel_PORelNum": "integer",
            "PORel_PORelOpen": "boolean",
            "PORel_Plant": "string",
            "PORel_PromiseDt": "date",
            "PORel_ReceivedQty": "numeric",
            "PORel_RelQty": "numeric",
            "PORel_ShortChar01": "string",
            "PORel_TranType": "string",
            "RcvDtl_InspectionPending": "string",
            "RcvDtl_OrderLine": "string",
            "RcvDtl_OrderNum": "string",
            "RcvDtl_ReceiptDate": "string",
            "Vendor_Name": "string",
        },
    },
    "GPT_CustSales": {
        "purpose": "Customer master with multi-year sales and quote history",
        "keywords": ["customer", "sales history", "contact", "account", "revenue", "top customer", "territory"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Calculated_Quote2022": "numeric",
            "Calculated_Quotes2022": "integer",
            "Calculated_sales2023": "numeric",
            "Calculated_sales2024": "numeric",
            "Calculated_sales2025": "numeric",
            "Calculated_salesFourYear": "numeric",
            "Customer_Address1": "string",
            "Customer_City": "string",
            "Customer_Country": "string",
            "Customer_CustID": "string",
            "Customer_CustNum": "integer",
            "Customer_Industry": "string",
            "Customer_Name": "string",
            "Customer_PhoneNum": "string",
            "Customer_State": "string",
            "Customer_Zip": "string",
            "ShipTo_Address1": "string",
            "ShipTo_City": "string",
            "ShipTo_Country": "string",
            "ShipTo_Name": "string",
            "ShipTo_State": "string",
            "ShipTo_ZIP": "string",
        },
    },
    # GPT_Daily: REMOVED — BAQ returns 404 (does not exist on Epicor server)
    "GPT_Bom": {
        "purpose": "Job Bill of Materials — all component parts on a job. CRITICAL for spare parts inquiries. Customer provides a PO, order number, part number, job number, or serial — use other BAQs to find the customer/job first, then query GPT_Bom to get the full parts list. Filter by customer name AND/OR order number AND/OR job number. WARNING: This BAQ is large — ALWAYS filter by customer name, order number, or job number. NEVER query without a filter (will timeout). For wear/replacement parts, look at Part_ClassID and Part_TypeCode to identify purchasable components.",
        "keywords": ["spare parts", "replacement parts", "BOM", "bill of materials", "components", "what parts", "reorder", "wear parts", "consumables", "job materials"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Customer_Company": "string",
            "Customer_Name": "string",
            "JobAsmbl_Description": "string",
            "JobHead_JobClosed": "boolean",
            "JobHead_JobComplete": "boolean",
            "JobHead_PartDescription": "string",
            "JobHead_PartNum": "string",
            "JobHead_ProdQty": "numeric",
            "JobMtl_AssemblySeq": "integer",
            "JobMtl_BuyIt": "boolean",
            "JobMtl_Description": "string",
            "JobMtl_FixedQty": "boolean",
            "JobMtl_IssuedQty": "numeric",
            "JobMtl_JobNum": "string",
            "JobMtl_MtlSeq": "integer",
            "JobMtl_PartNum": "string",
            "JobMtl_QtyPer": "numeric",
            "JobMtl_RequiredQty": "numeric",
            "JobProd_OrderNum": "integer",
            "OrderHed_PONum": "string",
            "Part_ClassID": "string",
            "Part_TypeCode": "string",
        },
    },
    "GPT_Bom2": {
        "purpose": "Job Bill of Materials v2 — component parts on a job with vendor info. PREFERRED over GPT_Bom for spare parts lookups. Filter by JobProd_OrderNum (integer), startswith(JobProd_JobNum, 'ORDER_PREFIX'), startswith(Customer_Name, 'NAME'), OrderHed_PONum, or Part_PartNum. Includes vendor name and part cost. NOTE: Only materials WITH a vendor appear (INNER JOIN on Vendor). For materials without vendors, use GPT_Bom instead.",
        "keywords": ["spare parts", "replacement parts", "BOM", "bill of materials", "components", "what parts", "reorder", "wear parts", "consumables", "job materials", "vendor", "supplier"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Customer_Name": "string",
            "Customer_Company": "string",
            "JobProd_OrderNum": "integer",
            "JobProd_JobNum": "string",
            "JobProd_RMANum": "integer",
            "JobProd_ProdQty": "numeric",
            "JobProd_DMRNum": "integer",
            "Part_ClassID": "string",
            "Part_TypeCode": "string",
            "Part_PartNum": "string",
            "Part_PartDescription": "string",
            "JobMtl_RequiredQty": "numeric",
            "JobMtl_QtyPer": "numeric",
            "JobMtl_IssuedQty": "numeric",
            "JobMtl_TotalCost": "numeric",
            "Vendor_Name": "string",
        },
    },
    "GPT_ShipmentHistory": {
        "purpose": "Historical shipment lookup with tracking numbers. Filter by order number, customer, or date. Use this whenever a customer asks about shipping status, tracking, or proof of delivery for ANY order (current or past).",
        "keywords": ["shipped", "tracking", "tracking number", "delivery", "shipment", "DHL", "UPS", "FedEx", "pack slip", "when did it ship", "proof of delivery"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Customer_CustID": "string",
            "Customer_CustNum": "integer",
            "Customer_Name": "string",
            "OrderHed_Company": "string",
            "OrderHed_PONum": "string",
            "ShipDtl_LineDesc": "string",
            "ShipDtl_OrderLine": "integer",
            "ShipDtl_OrderNum": "integer",
            "ShipDtl_OurInventoryShipQty": "numeric",
            "ShipDtl_OurJobShipQty": "numeric",
            "ShipDtl_PartNum": "string",
            "ShipHead_PackNum": "integer",
            "ShipHead_ShipDate": "date",
            "ShipHead_ShipViaCode": "string",
            "ShipHead_TrackingNumber": "string",
        },
    },
    "GPT_JobCosts": {
        "purpose": "Job costing — estimated vs actual labor, material, burden, subcontracting",
        "keywords": ["job cost", "margin", "overrun", "estimated", "actual", "profitability", "budget"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "JobAsmbl_DueDate": "date",
            "JobAsmbl_JobNum": "string",
            "JobAsmbl_PartNum": "string",
            "JobAsmbl_StartDate": "date",
            "JobAsmbl_TLABurdenCost": "numeric",
            "JobAsmbl_TLALaborCost": "numeric",
            "JobAsmbl_TLAMaterialCost": "numeric",
            "JobAsmbl_TLAProdHours": "numeric",
            "JobAsmbl_TLASubcontractCost": "numeric",
            "JobAsmbl_TLEBurdenCost": "numeric",
            "JobAsmbl_TLELaborCost": "numeric",
            "JobAsmbl_TLEMaterialCost": "numeric",
            "JobAsmbl_TLEProdHours": "numeric",
            "JobAsmbl_TLESubcontractCost": "numeric",
            "OrderDtl_DocExtPriceDtl": "numeric",
            "OrderDtl_DocUnitPrice": "numeric",
            "OrderDtl_OrderQty": "numeric",
            "OrderDtl_ProdCode": "string",
            "ShipDtl_LineDesc": "string",
            "ShipHead_ShipDate": "date",
        },
    },
    "GPT_MatlShortageReport": {
        "purpose": "Material shortages — what's needed for jobs but not yet issued",
        "keywords": ["shortage", "missing material", "holding up", "short", "material needed", "not issued"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "JobMtl_AssemblySeq": "integer",
            "JobMtl_Description": "string",
            "JobMtl_JobNum": "string",
            "JobMtl_MtlSeq": "integer",
            "JobMtl_PartNum": "string",
            "JobMtl_RelatedOperation": "integer",
            "JobMtl_RequiredQty": "numeric",
            "JobOper_OpDesc": "string",
            "PODetail_POLine": "integer",
            "PODetail_PONUM": "integer",
            "PORel_DueDate": "date",
            "PORel_PORelNum": "integer",
        },
    },
    "GPT_OTD2": {
        "purpose": "On-time delivery percentage by month, year, plant",
        "keywords": ["on time", "OTD", "delivery performance", "shipping on time", "late"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Calculated_PercentOnTime": "numeric",
            "Calculated_ShipMonth": "integer",
            "Calculated_ShipYear": "integer",
            "OrderRel_Plant": "string",
        },
    },
    "GPT_Open_Orders": {
        "purpose": "Order lookup by order number, customer, or status — includes BOTH open and closed lines. Best BAQ for 'status on order X' or 'what orders does customer Y have'. Filter on OrderRel_OrderNum for order number lookups. For order status queries, ALSO query GPT_ShipmentHistory to get tracking numbers.",
        "keywords": ["order status", "order number", "open order", "all companies", "industry", "ship to", "order lookup"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Customer_CreditHold": "boolean",
            "Customer_CustID": "string",
            "Customer_CustNum": "integer",
            "Customer_Name": "string",
            "OrderDtl_LineDesc": "string",
            "OrderDtl_OpenLine": "boolean",
            "OrderHed_Company": "string",
            "OrderHed_CreditOverride": "boolean",
            "OrderHed_EntryPerson": "string",
            "OrderHed_IndustrySegment_c": "string",
            "OrderHed_OrderDate": "date",
            "OrderHed_OrderHeld": "boolean",
            "OrderHed_PONum": "string",
            "OrderHed_Plant": "string",
            "OrderHed_ShipViaCode": "string",
            "OrderRel_BuyToOrder": "boolean",
            "OrderRel_DropShip": "boolean",
            "OrderRel_Make": "boolean",
            "OrderRel_NeedByDate": "date",
            "OrderRel_OrderLine": "integer",
            "OrderRel_OrderNum": "integer",
            "OrderRel_POLine": "integer",
            "OrderRel_PONum": "integer",
            "OrderRel_PartNum": "string",
            "OrderRel_Plant": "string",
            "OrderRel_ReqDate": "date",
            "ShipTo_Address1": "string",
            "ShipTo_City": "string",
            "ShipTo_Name": "string",
            "ShipTo_State": "string",
        },
    },
    "GPT_POhist": {
        "purpose": "Purchase order history — vendor spend, received quantities",
        "keywords": ["PO history", "vendor spend", "purchased", "bought", "supplier history"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "PODetail_DocUnitCost": "numeric",
            "PODetail_LineDesc": "string",
            "PODetail_PartNum": "string",
            "POHeader_BuyerID": "string",
            "POHeader_EntryPerson": "string",
            "POHeader_OrderDate": "date",
            "PORel_Company": "string",
            "PORel_DropShip": "boolean",
            "PORel_DueDate": "date",
            "PORel_JobNum": "string",
            "PORel_OpenRelease": "boolean",
            "PORel_POLine": "integer",
            "PORel_PONum": "integer",
            "PORel_Plant": "string",
            "PORel_ReceivedQty": "numeric",
            "PORel_WarehouseCode": "string",
            "Vendor_Name": "string",
        },
    },
    "GPT_Production3": {
        "purpose": "Production/manufacturing tracking — job status, operations, credit holds",
        "keywords": ["production", "manufacturing", "being built", "job status", "credit hold", "make", "in production"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Calculated_ActOper": "string",
            "Calculated_JobNum": "string",
            "Calculated_MFGComplete": "string",
            "Calculated_OnHandQty": "string",
            "Calculated_OpStartDate": "string",
            "Calculated_OpenValue": "numeric",
            "Calculated_Openqty": "numeric",
            "Calculated_Ordertotal": "numeric",
            "Customer_CreditHold": "boolean",
            "Customer_CustID": "string",
            "Customer_Name": "string",
            "JobHead1_JobNum": "string",
            "JobHead1_JobNum01": "string",
            "JobHead_JobNum": "string",
            "JobOper1_LastLaborDate": "string",
            "JobOper3_ActualStartDate": "string",
            "OpMaster1_OpDesc": "string",
            "OrderDtl_LineDesc": "string",
            "OrderDtl_OpenLine": "boolean",
            "OrderDtl_ProdCode": "string",
            "OrderDtl_QuoteLine": "integer",
            "OrderDtl_QuoteNum": "integer",
            "OrderDtl_SalesCatID": "string",
            "OrderDtl_UnitPrice": "numeric",
            "OrderHed_CreditOverride": "boolean",
            "OrderHed_CustNum": "integer",
            "OrderHed_EntryPerson": "string",
            "OrderHed_OrderComment": "string",
            "OrderHed_OrderHeld": "boolean",
            "OrderHed_OrderNum": "integer",
            "OrderHed_PONum": "string",
            "OrderHed_PayAccount": "string",
            "OrderHed_Plant": "string",
            "OrderHed_SalesRepList": "string",
            "OrderRel_BuyToOrder": "boolean",
            "OrderRel_Make": "boolean",
            "OrderRel_OpenRelease": "boolean",
            "OrderRel_OrderLine": "integer",
            "OrderRel_OrderNum": "integer",
            "OrderRel_OrderRelNum": "integer",
            "OrderRel_ReqDate": "date",
            "OrderRel_SellingReqQty": "numeric",
            "OrderRel_ShipToNum": "string",
            "PORel_Date01": "string",
            "PORel_POLine": "string",
            "PORel_PONum": "string",
            "PORel_PORelNum": "string",
            "PORel_PromiseDt": "string",
            "PORel_ShortChar01": "string",
            "PORel_TranType": "string",
            "ProdGrup_Company": "string",
            "ProdGrup_Description": "string",
            "ShipVia_Description": "string",
        },
    },
    "GPT_ShipTo": {
        "purpose": "Ship-to locations with customer details and multi-year sales",
        "keywords": ["ship to", "location", "territory", "sales rep", "address", "sales by location"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Calculated_Quote2022": "numeric",
            "Calculated_Quotes2022": "integer",
            "Calculated_salesFourYear": "numeric",
            "Customer_Address1": "string",
            "Customer_City": "string",
            "Customer_Country": "string",
            "Customer_Industry": "string",
            "Customer_Name": "string",
            "Customer_PhoneNum": "string",
            "Customer_State": "string",
            "Customer_Zip": "string",
            "ShipHead_CustNum": "integer",
            "ShipTo_Address1": "string",
            "ShipTo_City": "string",
            "ShipTo_Country": "string",
            "ShipTo_Name": "string",
            "ShipTo_State": "string",
            "ShipTo_ZIP": "string",
        },
    },
    "GPT_serialnumbers": {
        "purpose": "Serial number tracking — which serial went to which customer",
        "keywords": ["serial", "serial number", "traceability", "warranty", "DMR", "unit"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "Customer_Name": "string",
            "Part_PartDescription": "string",
            "SerialNo_CustNum": "integer",
            "SerialNo_DMRNum": "integer",
            "SerialNo_JobNum": "string",
            "SerialNo_PackLine": "integer",
            "SerialNo_PackNum": "integer",
            "SerialNo_PartNum": "string",
            "SerialNo_SNStatus": "string",
            "SerialNo_SerialNumber": "string",
            "SerialNo_WareHouseCode": "string",
        },
    },
    "gpt-JobOps": {
        "purpose": "Job operation details — hours, costs, completion, sequence",
        "keywords": ["job operation", "operation", "sequence", "hours", "job progress", "op complete"],
        "companies": ["BMC", "BME", "MAI"],
        "fields": {
            "JobOper_ActBurCost": "numeric",
            "JobOper_ActLabCost": "numeric",
            "JobOper_ActProdHours": "numeric",
            "JobOper_ActProdRwkHours": "numeric",
            "JobOper_ActSetupHours": "numeric",
            "JobOper_ActSetupRwkHours": "numeric",
            "JobOper_AssemblySeq": "integer",
            "JobOper_CommentText": "string",
            "JobOper_Company": "string",
            "JobOper_DaysOut": "numeric",
            "JobOper_Description": "string",
            "JobOper_DueDate": "date",
            "JobOper_DueHour": "numeric",
            "JobOper_EstProdHours": "numeric",
            "JobOper_EstScrap": "numeric",
            "JobOper_EstScrapType": "string",
            "JobOper_EstSetHours": "numeric",
            "JobOper_EstSetHoursPerMch": "numeric",
            "JobOper_EstUnitCost": "numeric",
            "JobOper_JobNum": "string",
            "JobOper_LaborRate": "numeric",
            "JobOper_LastLaborDate": "string",
            "JobOper_LoadHour": "numeric",
            "JobOper_OpCode": "string",
            "JobOper_OpComplete": "boolean",
            "JobOper_OpDesc": "string",
            "JobOper_OprSeq": "integer",
            "JobOper_PricePerCode": "string",
            "JobOper_PrimaryProdOpDtl": "integer",
            "JobOper_PrimarySetupOpDtl": "integer",
            "JobOper_ProdBurRate": "numeric",
            "JobOper_ProdComplete": "boolean",
            "JobOper_ProdLabRate": "numeric",
            "JobOper_ProdStandard": "numeric",
            "JobOper_PurPoint": "string",
            "JobOper_QtyCompleted": "numeric",
            "JobOper_QtyPer": "numeric",
            "JobOper_RcvInspectionReq": "boolean",
            "JobOper_ReworkBurCost": "numeric",
            "JobOper_ReworkLabCost": "numeric",
            "JobOper_RunQty": "numeric",
            "JobOper_SetUpCrewSize": "numeric",
            "JobOper_SetupBurRate": "numeric",
            "JobOper_SetupComplete": "boolean",
            "JobOper_SetupGroup": "string",
            "JobOper_SetupLabRate": "numeric",
            "JobOper_SetupPctComplete": "integer",
            "JobOper_StartDate": "date",
            "JobOper_StartHour": "numeric",
            "JobOper_StdBasis": "string",
            "JobOper_StdFormat": "string",
            "JobOper_SubContract": "boolean",
            "JobOper_UnitPrice": "numeric",
            "Vendor_Company": "string",
            "Vendor_Name": "string",
            "Vendor_VendorID": "string",
        },
    },
}


def get_baq_summary() -> str:
    """Build a concise summary of all BAQs for the AI system prompt."""
    lines = []
    for baq_id, info in BAQ_CATALOG.items():
        fields = ", ".join(info["fields"].keys())
        lines.append(
            f"### {baq_id}\n"
            f"**Purpose:** {info['purpose']}\n"
            f"**Companies:** {', '.join(info['companies'])}\n"
            f"**Fields:** {fields}\n"
        )
    return "\n".join(lines)


def get_baq_keywords() -> dict[str, list[str]]:
    """Return {baq_id: [keywords]} for quick matching."""
    return {baq_id: info["keywords"] for baq_id, info in BAQ_CATALOG.items()}
